name: handover
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  get_it: ^7.2.0
  get: ^4.6.5
  flutter_riverpod: ^0.14.0+3
  provider: ^6.0.0

  # Utils
  page_transition: ^2.0.9
  image_picker: ^0.8.4+3


  # local DB
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  flutter_local_notifications: 9.3.1

  # firebase
  firebase_messaging: ^14.0.1
  firebase_core: ^2.0.0
  firebase_in_app_messaging: ^0.7.0+2
  firebase_analytics: ^10.0.2
  firebase_dynamic_links: ^5.0.2


  # connectivity
  connectivity_plus: ^2.2.0
  http: ^0.13.4
  http_parser: ^4.0.1
  permission_handler: ^10.2.0
  icons_launcher: ^2.0.4
  pin_code_fields: ^7.4.0
  dotted_line: ^3.1.0
  dotted_border: ^2.0.0+3
  calendar_date_picker2: ^0.3.5
  platform_device_id: ^1.0.1
  table_calendar: ^3.0.9
  diox: ^5.0.0
  local_auth: ^2.1.3
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  hive: ^2.2.3
  logger: ^1.2.2
  flutter_dotenv: ^5.0.2
  flutter_card_swiper: ^5.0.1
  card_swiper: ^2.0.4
#  flutter_launcher_name: "^0.0.1"



#dependency_overrides:
#  hooks_riverpod: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#flutter_launcher_name:
#  name: "Ecokrib"
icons_launcher:
  image_path: 'assets/images/ecoKrib_logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

